---
galaxy_info:
  role_name: beegfs
  author: lab
  description: Deploy BeeGFS parallel filesystem (management, metadata, storage, client)
  min_ansible_version: "2.12"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble

dependencies: []
